GN_APK_HAS_JNI_LIBRARIES=yes

#apk Resolution
GN_APK_RESOLUTION=ldpi,xhdpi,hdpi,mdpi,nodpi,xxhdpi

GN_APK_LANGUAGE=zh_CN,en_US
GN_APK_PLATFORM_VERSION=4.2
GN_APK_MTK_PLATFORM=6589

#rule of zip name rule
#GN_ZIP_NAME_PALTFORM=6589
#GN_ZIP_NAME_ROM=4.2.0-4.2.4
#GN_ZIP_NAME_RESOLUTION=xhdpi_hdpi_mdpi
#GN_ZIP_NAME_PRODUCT_LINE=
#GN_ZIP_NAME_PRODUCT=GN708W_E3_E3T_E6_E6mini
